### ISSUE TITLE
transcript/gene quantification

### ISSUE THREAD

**Issue by droeatumn** [andymckenzie/BRETIGEA#10]
I have quantification per transcript, not gene as is the format for the input. Do you have advice how how I should handle this? Should I re-quantify at the gene level or find a tool that will aggregate the transcripts?

**Comment by andymckenzie** [comment]
Hello, yes, you will need a way to quantify expression at the gene level in order to run the functions in this package.  I think that either method should work and likely yield similar results

**Comment by droeatumn** [comment]
Thanks
