### ISSUE TITLE
Error when only one cell type is specified

### ISSUE THREAD

**Issue by mw201608** [andymckenzie/BRETIGEA#14]
When only one cell type is specified for functions brainCells & adjustBrainCells, the following error will return

Error in `colnames<-`(`*tmp*`, value = cell_types) : 
  attempt to set 'colnames' on an object with less than two dimensions

**Comment by andymckenzie** [comment]
Hello, 

I apologize for the big delay as I was busy with some other matters. 

Unfortunately, it seems that these functions in BRETIGEA cannot be properly run when only one cell type is specified. 

For some use cases, it might be possible to run BRETIGEA with multiple cell types specified and then select only the results from one cell type for downstream analysis. 

If future versions of BRETIGEA are made, this will be one area that is addressed. 

Best wishes, 
Andy
