### ISSUE TITLE
FindCells.R line 37: sum(inputMat[gene, ] > 0)

### ISSUE THREAD

**Issue by erskck-zi** [andymckenzie/BRETIGEA#15]
Hi, 

I would like to ask, how did you make the assumption that total expression of a gene across the samples must be greater than 0 to consider it as a marker? I'm a bit confused because, you used normalized RPKM which has been adjusted for RNA integrity number (RIN) and batch. The expression values can be negative too, since they are already adjusted. If you would use raw RPKM values (without adjusting it and log transformation), the assumption would be correct.  I don't understand why this value need to be greater than zero, if inputMat contains negative values. My last question, are the RPKM values log2 transformed?

Thanks, 
Ersoy

**Comment by andymckenzie** [comment]
Hi Ersoy,

Thank you for your thoughtful question. You raise a valid point about the potential edge case where a gene has negative expression values in all samples, which would cause the gene to be excluded as a marker. 

```
if (sum(inputMat[gene, ] > 0)) {
  ...
}
```

It's a logical operation, so if only one of the samples has a positive expression value it would not be a problem. I hadn't thought about this possible edge case, which might occur with unusual input matrices. I appreciate your feedback and will add this to the list of updates for the next version of BRETIGEA. 

Regarding your question about log transformation, the package is flexible with regard to the data input format. The gene expression input format used in the example data set from the Allen Brain Atlas has normalized RPKM values, which were adjusted for RNA integrity number (RIN) and batch. Note that all of the RPKM values are still positive in the example data set, `aba_marker_expression`. 

Best wishes, 
Andy

**Comment by erskck1** [comment]
Hi Andy, 

Thank you for answering my questions. It is clear to me now. 

Best wishes,
Ersoy
