### ISSUE TITLE
Marker gene list for each mouse brain cell type

### ISSUE THREAD

**Issue by rahil19** [andymckenzie/BRETIGEA#16]
Hi, 
As per the paper: https://doi.org/10.1038/s41598-021-97284-6
 it states the following in Supplementary section
"BRETIGEA also offers principal component analysis (PCA) as an option for cell type relative proportion estimation, along with sets of 1000 top consensus cell-specific genes for each cell type. "

I'm doing a single cell analysis of Brain tissues, with cell types as listed in your paper using scType to annotate clusters. Using your tool BRETIGEA, I was trying to extract 1000 top consensus marker genes for each cell type but was unsuccessful in doing so. Cell types I'm providing in the reference marker list: Astrocyte, Endothelial, Microglia, Neuron, Oligodendrocyte, OPC.

So far, with your tool, I'm only able to extract 20 genes with the command
```
> ct_res = brainCells(aba_marker_expression, nMarker = 1000, celltypes = "ast")
    markers cell
1      AQP4  ast
2   ALDH1L1  ast
3    BMPR1B  ast
4   SLC14A1  ast
5      MLC1  ast
6     FGFR3  ast
7  SLC25A18  ast
8      GLI3  ast
9      GFAP  ast
10   ACSBG1  ast
11   SLC4A4  ast
12     GJA1  ast
13     GJB6  ast
14 SLC39A12  ast
15      AGT  ast
16   CHRDL1  ast
17   SLC1A2  ast
18   CLDN10  ast
19     SOX9  ast
20  PPP1R3C  ast
```
With the error reported at the end of the command run
Error in `colnames<-`(`*tmp*`, value = cell_types) : 
  attempt to set 'colnames' on an object with less than two dimensions

Could you please let us know how to obtain 1000 marker list per cell type using your BRETIGEA tool?

**Comment by andymckenzie** [comment]
Hi rahil19, 

Thank you for your question and for using BRETIGEA. 

I believe that this problem is occurring because you are specifying only one cell type.  Unfortunately, BRETIGEA cannot be properly run when only one cell type is specified.

For some use cases, it should be possible to run BRETIGEA with multiple cell types specified and then select only the results from one cell type for downstream analysis.

If future versions of BRETIGEA are made, this will be one area that is addressed.

**Comment by rahil19** [comment]
Hi Andy,

Thanks for the quick response. Even when I request for all celltypes, it displays the top 20 for ast cell type, but saves the following info

```
> head(ct_res)
                    ast          end          mic         neu         oli         opc
X488395315 -0.040976558 -0.047289570 -0.024907636  0.02264002 -0.01947397 -0.02503821
X496100277  0.039178643  0.011220440 -0.001227078 -0.13613602  0.13236668  0.13242155
X496100278  0.074205476  0.088834022  0.115826619 -0.13607897  0.15343410  0.16303552
X496100279 -0.009130784 -0.005993897  0.010381132  0.06802770 -0.01949598 -0.02189551
X496100281  0.113689595 -0.006266652  0.082538817  0.01169456 -0.02430284 -0.02581615
X496100283 -0.044073116 -0.026795044 -0.035604719  0.04497771 -0.02205507 -0.01905020
> tail(ct_res)
                   ast         end          mic         neu          oli          opc
X496100666  0.09871245 -0.01790293  0.133815637 -0.04393163 -0.020949491 -0.016752770
X496100667 -0.06763452 -0.03970916 -0.059009193  0.04683017 -0.020316776 -0.023413972
X496100669 -0.01361837 -0.05041813 -0.050824738 -0.01761807  0.075611955  0.068200071
X496100670 -0.04345309 -0.02943731 -0.037839178  0.05207951 -0.026976571 -0.028589670
X496100671  0.02898702  0.02387866 -0.006898805 -0.03958499 -0.005130079 -0.009729056
X496100672  0.05699167  0.05529206  0.021242052 -0.04578126  0.071895377  0.080629323
```

I don't know what Xnumber stands for here. Definitely not gene id

Command
```
ct_res = brainCells(aba_marker_expression, nMarker = 1000, celltypes = c("ast", "end", "mic", "neu", "oli", "opc"))
```

Thanks, Rahil

**Comment by andymckenzie** [comment]
Hello,

To clarify, you are no longer receiving the error correct?

The purpose of the package is to calculate relative cell type proportions
in each sample of a gene expression data set. Do the Xnumbers correspond to
the sample id’s in the data set that you inputted?

If you want the marker gene symbols themselves, they should be available in
the supplementary section of the associated paper.
