### ISSUE TITLE
extracting cell-specific expression from bulk tissue matrix through BRETIGEA/complete deconvolution

### ISSUE THREAD

**Issue by klai001** [andymckenzie/BRETIGEA#5]
Hi developers of BRETIGEA
I have the bulk tissue brain expression matrix which i want to deconvolute to specifically my cell type of interest's expression.
 
With mycelltype containing a character of vectors with that cell's specific gene signature,

i used the myadjcells<-adjustcells (bulkmatrix,svd,mycelltype,addMeans = FALSE,formula = NULL, verbose = TRUE) function and ran them successfully.

Does it mean complete deconvolution has been performed? where myadjcells[["expression"]] will refer to the expression matrix of specifically my cell-type?

**Comment by andymckenzie** [comment]
Hi klai001, 

Thanks for using BRETIGEA and I apologize for the delay in response. 

Here is the description of adjust cells: "This function uses a linear model to adjust each row of gene expression for cell types, taking the residuals from the linear model for downstream analysis. Other covariates can be included as well, if they are defined in the current environment, through the use of the formula argument."

Specifically, what adjustcells will do is: 

- calculate the relative cell type proportions of each of the cells that you input,
- using a linear model, adjust each row of the expression matrix to remove the predicted effects of the differences in cell types across conditions, and 
- return the adjusted expression matrix. 

So it is not quite true that this is the expression matrix of your cell type. Rather, it is meant to refer to the expression matrix of the tissue with the linear effects of the inputted cell types removed, under the assumptions of this statistical model. 

Hope that helps.

**Comment by klai001** [comment]
Hi Andy,
thanks for your clarification
is there currently an argument in BRETTIGEA though that i can then call upon for extracting cell-type specific expression from bulk tissue?

**Comment by andymckenzie** [comment]
Hi klai001, 

Unfortunately, no, there is not an option for that in BRETIGEA.
