### ISSUE TITLE
Are genes in markers_df_mouse_brain.rda sorted by relevance for each specific cell type?

### ISSUE THREAD

**Issue by fbrundu** [andymckenzie/BRETIGEA#6]
I am using `markers_df_mouse_brain.rda` under the data folder as a reference list for cell type markers.
Are the genes sorted by importance as described in the paper in subsection "Ranking genes by their cell type-associated expression across data sets."? It seems so, for example, Aqp4 is the top one for Astrocytes... thanks!

**Comment by andymckenzie** [comment]
Hi and thanks for using BRETIGEA. 
Yeah, the genes in this list are ranked by their specificity for that cell type.

**Comment by fbrundu** [comment]
Thanks!
