### ISSUE TITLE
Input data

### ISSUE THREAD

**Issue by norabv139** [andymckenzie/BRETIGEA#8]
I'm trying to use the r R BRETIGEA package and can't seem to load my data. No matter how I read it, it comes back with:

  Error in brainCells(data, nMarker = 50, species = "combined", celltypes = c("ast",  : 
  At least one marker gene symbol must be present in the rownames of the input matrix.

I'm sure it's something silly but I just can't find the problem, would someone be able to help? I'm using mouse RNAseq data, first row mgi symbols as identifiers, then every row is a different sample from the experiment.

Thanks!

**Comment by andymckenzie** [comment]
Hello and thanks for using BRETIGEA. 

For the brainCells() function, here is the input data format. 

> inputMat: Gene expression data frame or matrix, with rownames
>           corresponding to gene names, some of which are marker genes,
>           and columns corresponding to samples.

So the rows should be gene symbols and the columns should be samples. It sounds like you may need to transpose your input data. 

Here is a brief tutorial I just found on how to transpose a data frame that might be helpful. https://rpubs.com/Mentors_Ubiqum/Transpose_Dataframe

**Comment by norabv139** [comment]
Hi Andy,

Thanks for you quick reply!

I have transposed them, that's why I can't think of what's going on...
