### ISSUE TITLE
RNA-seq input values

### ISSUE THREAD

**Issue by droeatumn** [andymckenzie/BRETIGEA#9]
The input values for the RNA-seq data are raw counts, is that right? As opposed to TPM, etc. I can find it explicitly in the documentation.

**Comment by andymckenzie** [comment]
Hello and thanks for using BRETIGEA. The package is flexible on the data input format. The gene expression input format used in the example data set from the Allen Brain Atlas was normalized RPKM values, which was adjusted for RNA integrity number (RIN) and batch.

**Comment by droeatumn** [comment]
Thank you.
